---
deployment:
  tasks:
    - export REPOPATH=/home/kuratnik/repo/Portfolio*
    - export SITEPATH=/home/kuratnik/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
    